language: node_js
node_js:
  - "v4"
# install fixtures deps
before_install:
  - cd test/fixtures; npm i
  - cd node_modules; rm -rf predator-kit; ln -sf ../../.. predator-kit
  - cd ../../..
script: "npm run test"
notifications:
  email: false