language: node_js
node_js:
  - "v4"
# install fixtures deps
before_install:
  - cd test/fixtures/node_modules
  - pwd
  - ln -sf ../../..
  - pwd
  - cd ../
  - pwd
  - npm i
script: "npm run test"
notifications:
  email: false