language: node_js
node_js:
  - "v4"

# install fixtures deps
before_install:
  - cd test/fixtures
  - npm i
  - cd node_modules
  - ln -sf ../../../../predator-kit predator-kit
script: "npm run test"
notifications:
  email: false